sudo: required
services:
  - docker

before_install:
  - docker build -t venec/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true venec/react-test npm test

after_success:
  - docker build -t venec/multi-client ./client
  - docker build -t venec/multi-nginx ./nginx
  - docker build -t venec/multi-server ./server
  - docker build -t venec/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker hub
  - docker push venec/multi-client
  - docker push venec/multi-nginx
  - docker push venec/multi-server
  - docker push venec/multi-worker
